apiVersion: v1
kind: Service
metadata:
  labels:
    component: admin-server
    app: petclinic
  name: admin-server
spec:
  ports:
  - name: http8082
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    component: admin-server
    app: petclinic
  sessionAffinity: None
  type: "{{ .Values.service.adminServer.type }}"
