apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubernetes.io/change-cause: {{ .Values.image.changeCause | quote }}
    helm.sh/hook-weight: "20"
  generation: 1
  labels:
    component: api-gateway
    app: petclinic
  name: api-gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      component: api-gateway
      app: petclinic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      annotations:
        kubernetes.io/change-cause: {{ .Values.image.changeCause | quote }}
      labels:
        component: api-gateway
        app: petclinic
    spec:
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
        - --spring.profiles.active=docker
        - --server.port=8080
        image: "{{ .Values.image.repository }}/spring-petclinic-api-gateway:{{ .Values.image.tag }}"
        imagePullPolicy: "Always"
        name: api-gateway
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
