apiVersion: v1
kind: Service
metadata:
  labels:
    component: api-gateway
    app: petclinic
  name: api-gateway
spec:
  ports:
  - name: http8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: api-gateway
    app: petclinic
  sessionAffinity: None
  type: "{{ .Values.service.apiGateway.type }}"
