apiVersion: v1
kind: Service
metadata:
  labels:
    component: config-server
    app: petclinic
  name: config-server
spec:
  ports:
  - name: http8888
    port: 8888
    protocol: TCP
    targetPort: 8888 
  selector:
    component: config-server
    app: petclinic
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
