apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    helm.sh/hook-weight: "1"
  generation: 1
  labels:
    component: config-server
    com.docker.service.name: config-server
    app: petclinic
  name: config-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      component: config-server
      app: petclinic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: config-server
        app: petclinic
    spec:
      containers:
      - image: "{{ .Values.image.repository }}/spring-petclinic-config-server:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: config-server
        ports:
        - containerPort: 8888
          name: http8888
          protocol: TCP
        #readinessProbe:
        #  failureThreshold: 6
        #  # this is currenctly to check
        #  httpGet:
        #    path: /
        #    port: 8888
        #    scheme: HTTP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
