apiVersion: v1
kind: Service
metadata:
  labels:
    component: customers-service
    app: petclinic
  name: customers-service
spec:
  ports:
  - name: http8761
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    component: customers-service
    app: petclinic
  sessionAffinity: None
  type: ClusterIP
