apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: {{ .Values.image.changeCause | quote }}
    deployment.kubernetes.io/revision: "1"
    helm.sh/hook-weight: "10"
  generation: 1
  labels:
    component: customers-service
    app: petclinic
  name: customers-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      component: customers-service
      app: petclinic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      annotations:
        kubernetes.io/change-cause: {{ .Values.image.changeCause | quote }}
      labels:
        component: customers-service
        app: petclinic
    spec:
      containers:
      # @ todo check if it's needed
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
        - --spring.profiles.active=docker
        - --server.port=8081
        image: "{{ .Values.image.repository }}/spring-petclinic-customers-service:{{ .Values.image.tag }}"
        imagePullPolicy: "Always"
        name: customers-service
        ports:
        - containerPort: 8081
          name: http8081
          protocol: TCP
        #readinessProbe:
        #  failureThreshold: 6
        #  # this is currenctly to check
        #  httpGet:
        #    path: /
        #    port: 8081
        #    scheme: HTTP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
