apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: {{ .Values.image.changeCause | quote }}
    deployment.kubernetes.io/revision: "1"
    helm.sh/hook-weight: "2"
  generation: 1
  labels:
    component: discovery-server
    app: petclinic
  name: discovery-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      component: discovery-server
      app: petclinic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: {{ .Values.image.changeCause | quote }}
      creationTimestamp: null
      labels:
        component: discovery-server
        app: petclinic
    spec:
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://config-server:8888
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
        - --spring.profiles.active=docker
        - --server.port=8761
        image: "{{ .Values.image.repository }}/spring-petclinic-discovery-server:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: discovery-server
        ports:
        - containerPort: 8761
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
