apiVersion: v1
kind: Service
metadata:
  labels:
    component: discovery-server
    app: petclinic
  name: discovery-server
spec:
  ports:
  - name: http8761
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    component: discovery-server
    app: petclinic
  sessionAffinity: None
  type: ClusterIP
