{{- if .Values.ingress.enabled -}}
{{- $fullName := include "spring-petclinic-microservices.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic-ingress
  labels:
    app.kubernetes.io/name: {{ include "spring-petclinic-microservices.name" . }}
    helm.sh/chart: {{ include "spring-petclinic-microservices.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: petclinic-ingress
    app: petclinic
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.hosts.hostAdminServer }}
    http:
      paths:
      - path: "/*"
        backend:
          serviceName: admin-server
          servicePort: 9090
  - host: {{ .Values.ingress.hosts.hostApiGateway }}
    http:
      paths:
      - path: "/*"
        backend:
          serviceName: api-gateway
          servicePort: 8080
{{- end }}
