apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    helm.sh/hook-weight : "11"
  labels:
    component: visits-service
    app: petclinic
  name: visits-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      component: visits-service
      app: petclinic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: visits-service
        app: petclinic
    spec:
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
        - --spring.profiles.active=docker
        - --server.port=8082
        image: "{{ .Values.image.repository }}/spring-petclinic-visits-service:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: visits-service
        ports:
        - containerPort: 8082
          name: http8082
          protocol: TCP
        #readinessProbe:
        #  failureThreshold: 6
        #  # this is currenctly to check
        #  httpGet:
        #    path: /
        #    port: 8082
        #    scheme: HTTP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5

